name: compile & stash

on:
  push:
    branches:
      - 'development'
      - 'devel/*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc-arm-non-eabi

      - name: Get the source
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Run cmake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
